### ISSUE TITLE
Please provide Dockerfile and Docker Hub Repository

### ISSUE THREAD

**Issue by InAnimaTe** [byrnedo/dockdash#1]
Decrease barriers to entry for trying out this cool utility!

**Comment by byrnedo** [comment]
Hi @InAnimaTe 

Not sure how this would work since this tool listens to the docker port itself. 

Would it be better if I just uploaded builds for different architectures?

**Comment by xcellardoor** [comment]
Could you tell me how to build/run this? I'm not too familiar with Go :(

**Comment by byrnedo** [comment]
I'll update the readme in a bit and let you know, otherwise if you're on
ubuntu:

```
sudo apt-get install golang-go
```

Then in the project

```
go get
```

then

```
go build
```

That should make a binary called `dockdash`.

You can just run it as ./dockdash then

**Comment by xcellardoor** [comment]
Thanks got it going :)

**Comment by byrnedo** [comment]
No problem :)

**Comment by InAnimaTe** [comment]
You could tell people to use `--net=host` or if it supports using the socket, `-v /var/run/docker.sock:/var/run/docker.sock`.

**Comment by byrnedo** [comment]
Good idea, right now it looks at ENVs
Den 22 okt 2015 18:10 skrev "Mario Loria" notifications@github.com:

**Comment by byrnedo** [comment]
Just got what you mean now, will make a dockerfile
Den 22 okt 2015 18:17 skrev "Donal Byrne" byrnedo@tcd.ie:

**Comment by byrnedo** [comment]
@InAnimaTe  You can now just run `make try` and it'll build and run an instance inside docker (mounts the socket) :)

**Comment by byrnedo** [comment]
There's now a docker hub repo for this too.

**Comment by InAnimaTe** [comment]
Yay! thanks for your hard work on this!

**Comment by byrnedo** [comment]
No problem :)
