### ISSUE TITLE
Improvements to the deb package

### ISSUE THREAD

**Issue by peterrosell** [byrnedo/dockdash#3]
Thanks for this tool Donal!
It would be great if you could fix some problems with the deb package.
Tested it with lintian and got some errors and warnings. See output below. I don't have the answer to the different errors and warnings, but I guess you can find detailed info online.

```
# lintian dockdash_0.11_amd64.deb 
E: dockdash: unstripped-binary-or-object usr/local/bin/dockdash
W: dockdash: hardening-no-relro usr/local/bin/dockdash
W: dockdash: missing-depends-line
E: dockdash: changelog-file-missing-in-native-package
E: dockdash: control-file-has-bad-permissions postinst 0775 != 0755
E: dockdash: control-file-has-bad-owner postinst donalb/donalb != root/root
W: dockdash: unknown-control-file prerem
E: dockdash: no-copyright-file
W: dockdash: unknown-section base
E: dockdash: wrong-file-owner-uid-or-gid usr/ 1001/1001
W: dockdash: non-standard-dir-perm usr/ 0775 != 0755
E: dockdash: wrong-file-owner-uid-or-gid usr/local/ 1001/1001
W: dockdash: non-standard-dir-perm usr/local/ 0775 != 0755
E: dockdash: wrong-file-owner-uid-or-gid usr/local/bin/ 1001/1001
E: dockdash: dir-in-usr-local usr/local/bin/
W: dockdash: non-standard-dir-perm usr/local/bin/ 0775 != 0755
E: dockdash: wrong-file-owner-uid-or-gid usr/local/bin/dockdash 1001/1001
E: dockdash: file-in-usr-local usr/local/bin/dockdash
W: dockdash: file-in-unusual-dir usr/local/bin/dockdash
```

**Comment by byrnedo** [comment]
Hey Peter, hope you're well :)

Yeah, I made an effort to build a fully compatible debian a while back but failed. 
I'll set a little time aside to clean it up.

Have you a use case where you need a 'good quality' package? Is the quality blocking you using it?

**Comment by peterrosell** [comment]
The main problem is that the installed file is owned by user ID 1001:1001 (donald). That means that if installed on a multi user machine one of the normal users will have write access to a file in usr/local/bin. That person can change the file and make others run it from their PATH. Normally installed programs are owned by root.

I have never made a deb package by myself and just did a quick googling yesterday and saw that people had problem with setting permission correctly in packages. I can see if I can find a solution to it. :-)

**Comment by byrnedo** [comment]
I'm gonna close this since I'm not going to get round to it.
